### ISSUE TITLE
many powers dont work

### ISSUE THREAD

**Issue by Poopermonkinatr** [doombubbles/powers-in-shop#1]
self explanitory title

**Comment by doombubbles** [comment]
Gonna need more information than that lol. You're using Mod Helper 3.0? If that not's the issues then I'd need to see logs / screenshots

**Comment by Poopermonkinatr** [comment]
accually they work now

**Comment by Poopermonkinatr** [comment]
i had to update it

**Comment by doombubbles** [comment]
Ok nice 👍
